development:
  adapter: postgresql
  database: demo4_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: demo4_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  pool: 5
  database: demo4_prod
  timeout: 5000
